# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ed2fc5d14dcf12435585ea4b5b384364163d1fa6fd3a0f33831c732cc0d232a9dd4af364a43c279299975bce1b30ee7ed49bafe50c095de2df8938dc9452b444

test:
  secret_key_base: 775bdca96d221ed8240dbec628e3a10d2a80d3c16abc1cc99673ac1e1208ae8e02f31bee73a109beeb52f23b5befa0126b8d71310903a8fa17fb60751db5751a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
